---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: system
  namespace: flux-system
spec:
  interval: 5m0s
  ref:
    branch: main
  secretRef:
    name: flux-system
  url: ssh://git@github.com/kilianops/system.git