---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: system-monitoring
  namespace: flux-system
spec:
  path: ./monitoring
  interval: 5m0s
  serviceAccountName: kustomize-controller
  dependsOn: 
    - name: system-core-controllers
  sourceRef:
    name: system
    kind: GitRepository
  wait: true
  prune: true
  timeout: 5m0s